---
title: "Functional Geometry (1982)"
author: "Matthew Henderson"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Square Limit}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Man

* http://users.ecs.soton.ac.uk/peter/funcgeo.pdf
* http://www.frank-buss.de/lisp/functional.html

```{r setup, include = FALSE, cache = FALSE, include = FALSE}
library(knitr)
opts_chunk$set(
  fig.width = 3,
  fig.height = 3,
  message = FALSE,
  echo = TRUE,
  warning = FALSE
)
```

```{r, message = FALSE, fig.cap = "Figure 1"}
library(funcgeo)

plot(man)
```

```{r, fig.cap = "Figure 7"}
plot(beside(man, man))
```

```{r}
plot(above(man, man))
```

```{r, fig.cap = "Figure 15"}
plot(rot(man))
```

```{r}
plot(quartet(man, man, man, man))
```

```{r}
plot(cycle(man))
```

```{r, fig.cap = "Figure 18"}
plot(fish_p)
```

```{r, fig.cap = "Figure 19"}
plot(fish_q)
```

```{r, fig.cap = "Figure 20"}
plot(fish_r)
```

```{r, fig.cap = "Figure 21"}
plot(fish_s)

```
```{r, fig.cap = "Figure 22: t = quartet(p, q, r, s)"}
t <- quartet(fish_p, fish_q, fish_r, fish_s)
plot(t)
```

```{r, fig.cap = "Figure 23: u = cycle(rot(q))"}
u <- cycle(rot(fish_q))
plot(u)
```

```{r, fig.cap = "Figure 24: u = cycle(rot(t))"}
plot(cycle(rot(t)))
```

```{r, fig.cap = "Figure 25: side1"}
nill <- grid::nullGrob()
side1 <- quartet(nill, nill, rot(t), t)
plot(side1)
```

```{r, fig.cap = "Figure 26: side2"}
side2 <- quartet(side1, side1, rot(t), t)
plot(side2)
```

```{r, fig.cap = "Figure 27: corner1"}
corner1 <- quartet(nill, nill, nill, u)
plot(corner1)
```

```{r, fig.cap = "Figure 28: corner2"}
corner2 <- quartet(corner1, side1, rot(side1), u)
plot(corner2)
```

footnotes^[P. Henderson "Functional Geometry"]
